name = "JuliaTokai_202011"
uuid = "488ce05f-ad02-41a7-a099-398b49255361"
authors = ["GOTOH Shunsuke <antimon2.me@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
julia = "1.5"
